version: "3.8"

services:
  jeager:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"   # Jaeger UI
      - "9411:9411"     # Zipkin collector port
      - "6831:6831/udp" # Jaeger compact thrift over UDP
      - "6832:6832/udp" # Jaeger binary thrift over UDP
      - "5778:5778"     # Jaeger agent HTTP management port
      - "4317:4317"     # Jaeger agent gRPC HTTP collector port
      - "4318:4318"     # Jaeger agent gRPC HTTP collector port for encrypted spans
      - "14250:14250"   # Jaeger gRPC trace ingestion port
      - "14268:14268"   # Jaeger gRPC HTTP internal service communication port
      - "14269:14269"   # Jaeger gRPC HTTP internal service communication port for encrypted messages
